package com.dicoding.stories.shared.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF226A4C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFAAF2CB)
val onPrimaryContainerLight = Color(0xFF002113)
val secondaryLight = Color(0xFF4D6357)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0E8D8)
val onSecondaryContainerLight = Color(0xFF0A1F16)
val tertiaryLight = Color(0xFF3D6473)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC0E9FA)
val onTertiaryContainerLight = Color(0xFF001F29)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FBF5)
val onBackgroundLight = Color(0xFF171D19)
val surfaceLight = Color(0xFFF5FBF5)
val onSurfaceLight = Color(0xFF171D19)
val surfaceVariantLight = Color(0xFFDCE5DD)
val onSurfaceVariantLight = Color(0xFF404943)
val outlineLight = Color(0xFF707973)
val outlineVariantLight = Color(0xFFC0C9C1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322E)
val inverseOnSurfaceLight = Color(0xFFEDF2EC)
val inversePrimaryLight = Color(0xFF8ED5B0)
val surfaceDimLight = Color(0xFFD6DBD6)
val surfaceBrightLight = Color(0xFFF5FBF5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5EF)
val surfaceContainerLight = Color(0xFFEAEFE9)
val surfaceContainerHighLight = Color(0xFFE4EAE4)
val surfaceContainerHighestLight = Color(0xFFDEE4DE)
